language: scala
sudo: required
dist: trusty
env:
  global:
    - _JAVA_OPTIONS="-Dakka.test.timefactor=3"
scala:
   - 2.12.11
cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier
before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
jdk:
   - openjdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
