language: scala
sudo: required
dist: trusty
env:
  global:
    - _JAVA_OPTIONS="-Dakka.test.timefactor=3"
scala:
   - 2.12.10
jdk:
   - openjdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
