FROM jelastic/jetty:9.4.49-openjdk-1.8.0_352

USER root

ENV JAVA_OPTS="-Xmx2G"

ENV CONTAINER_HTTP_PORT="8088"

RUN mkdir -p /etc/hydra && mkdir -p /var/log/hydra && mkdir /ps-publish

EXPOSE 8088

COPY ps-publish/ /ps-publish

ENTRYPOINT ["/ps-publish/bin/hydra-ingest"]