name: Tests

on:
  pull_request:
    paths:
      - '**.scala'
      - '**.java'
      - 'build.sbt'
      - 'project/**'
  push:
    paths:
      - '**.scala'
      - 'build.sbt'
      - 'project/**'
      - '**.java'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up OpenJDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests
        run: sbt test

      # - name: Build SBT Docker Image
      #   run: docker build -t scala-sbt-openjdk:2.12.11-1.5.8-1.8 .

      # - name: Run SBT Tests
      #   run: docker run -w /hydra -v $(pwd):/hydra scala-sbt-openjdk:2.12.11-1.5.8-1.8 sbt test
      #   timeout_minutes: 10
